# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
category: Other
description: fpic is a new Haskeleton package.
ghc-options: -Wall
github: xtendo-org/fpic
license: MIT
maintainer: XT
name: fpic
synopsis: A new Haskeleton package.
version: '0.0.0'

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

dependencies:
- aeson
- text

ghc-options:
- -optl-static
- -fPIC

library:
  dependencies:
  - base
  source-dirs: library

executables:
  fpic:
    dependencies:
    - base
    - fpic
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: executable

tests:
  fpic-test-suite:
    dependencies:
    - base
    - fpic
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite

benchmarks:
  fpic-benchmarks:
    dependencies:
    - base
    - fpic
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: benchmark
